### ISSUE TITLE
No usar github

### ISSUE THREAD

**Issue by Akronix** [LibreLabUCM/LiberarFdI#1]
Si queremos que las asignaturas se puedan hacer 100% con herramientas libres, se debería dar la oportunidad de no tener que usar repositorios de código que son privativos, y eso incluye github, bitbucket y otros.

En su lugar, deberíamos proponer y dar ejemplo usando otras alternativas, que además hay varias, como gitlab, phabricator o gogs (un calco de github)

**Comment by jesusjda** [comment]
https://liberarfdi.librelabucm.org

**Comment by Akronix** [comment]
En efecto, ahora usamos [mediawiki](https://www.mediawiki.org/wiki/MediaWiki) :smiley:
